title: Kumar Group
email: n.kumar@unsw.edu.au
description: >-
  Naresh Kumar Medicinal Chemistry Research Group at UNSW Sydney.
  We focus on drug discovery, medicinal chemistry, and computational drug design.
baseurl: ""
url: "https://nareshkumar.com.au"
timezone: Australia/Sydney
future: true
twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true

exclude:
  - "Naresh Kumar (0000-0002-0951-9621) - ORCID _ Connecting Research and Researchers.html"
